name: LearnPythonforResearch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - requests
  - xlrd
  - openpyxl
  - seaborn
  - bokeh
  - hickle
  - lxml
  - cssselect
  - PyTables
  - plotnine
  - plotly
  - selenium
  - pip:
    - qgrid
    - requests-html